package: initial split from `logdna-agent`
logdna/agent-linux pull request #1
Opened 2020-10-06 17:50 UTC by darinspivey

This is copied from `logdna-agent` with removals for
everything that is not Linux-based.  Future enhancements
for the README and code are to come in other PRs.

Semver: patch

2020-10-06 17:57 UTC, darinspivey commented on CONTRIBUTING.md
> +
Remove these

2020-10-06 17:57 UTC, darinspivey commented on CONTRIBUTING.md
> +```
Remove

2020-10-06 17:57 UTC, darinspivey commented on README.md
> +LogDNA Agent streams from log files to your LogDNA account. Works with Linux, Windows, and macOS Servers.
Prune the OS mention

2020-10-06 17:57 UTC, darinspivey commented on docs/kubernetes.md
> +# Kubernetes Logging
Should we remove the k8s discussion at this point?  I feel like if someone is here, then we shouldn't need to talk about this in this repo

2020-10-06 17:57 UTC, darinspivey commented on CONTRIBUTING.md
> +# windows
Remove

2020-10-06 17:57 UTC, darinspivey commented on CONTRIBUTING.md
> +# windows
Remove

2020-10-06 17:57 UTC, darinspivey commented on CONTRIBUTING.md
> +```
Remove

2020-10-06 17:57 UTC, darinspivey commented on README.md
> +# On Windows, this will generate a config file at: C:\ProgramData\logdna\logdna.conf
Remove

2020-10-06 17:57 UTC, darinspivey commented on README.md
> +# on Windows, C:\ProgramData\logs is monitored/added by default (recursively). You can optionally specify more folders
Remove

2020-10-06 17:57 UTC, darinspivey commented on README.md
> +## Windows Logging
Remove

2020-10-06 17:57 UTC, darinspivey commented on lib/file-utilities.js
> +  // glob patterns always use / (even on windows)
Prune OS

2020-10-06 17:57 UTC, darinspivey commented on index.js
> +  const isAdmin = os.platform() === 'win32' ? require('is-administrator')() : process.getuid() === 0
Remove windows mention

2020-10-06 17:57 UTC, darinspivey commented on lib/config.js
> +, DEFAULT_CONF_FILE: os.platform() !== 'win32' ? '/etc/logdna.conf' : path.join(process.env.ALLUSERSPROFILE, '/logdna/logdna.conf')
Remove win32 conditionals everywhere

2020-10-06 17:57 UTC, darinspivey commented on lib/file-utilities.js
> +      nocase: os.platform() !== 'win32' && globpattern.indexOf('*') === -1
Remove win32

2020-10-06 17:57 UTC, darinspivey commented on lib/file-utilities.js
> +    if (os.platform() !== 'win32' && config.TAIL_MODE === 'unix') {
Remove win32

2020-10-06 17:57 UTC, darinspivey commented on tools/README.md
> +- Update the `version` in [`logdna-agent.nuspec`](./files/win32/logdna-agent.nuspec#L7)
Remove mac and windows mention

2020-10-06 18:03 UTC, darinspivey commented on tools/files/logdna.gpg
> +-----BEGIN PGP PUBLIC KEY BLOCK-----
@smusali can this come out?  What's this for again?

2020-10-06 18:06 UTC, darinspivey commented
Also needs our 90-char eslint config loaded and fixed up

2020-10-06 18:35 UTC, darinspivey commented on lib/config.js
> +, DEFAULT_WINTAIL_FILE: path.join(process.env.ALLUSERSPROFILE, '/logdna/winTail.ps1')
@smusali can this env var come out entirely?

2020-10-06 19:07 UTC, ydshah2 commented
Can we add the JIRA ticket on this?

2020-10-06 21:15 UTC, mdeltito commented on .npmrc
> +package-lock=false
I know this is just being pulled over from `logdna-agent` but this isn't a library and we want reproducible builds, and so probably warrants a lockfile.

2020-10-06 21:15 UTC, mdeltito commented on docs/kubernetes.md
> +# Kubernetes Logging
I agree with that, there will be no "history" of k8s support here so this isn't relevant.

2020-10-06 21:15 UTC, mdeltito commented on lib/config.js
> +, DEFAULT_WINTAIL_FILE: '/etc/winTail.ps1'
this appears to be unused, here and in the legacy repo

2020-10-06 21:15 UTC, mdeltito commented on CONTRIBUTING.md
> +This takes a bit of time and will output a binary at `./logdna-agent` (or `.\logdna-agent.exe` if on Windows). For the initial build, majority of time will be spent building node.js. Subsequent build
windows reference here

2020-10-06 21:15 UTC, mdeltito commented on lib/file-utilities.js
> +    if (os.platform() !== 'win32' && config.TAIL_MODE === 'unix') {
still seeing the win32 condition here

2020-10-06 21:15 UTC, mdeltito commented on README.md
> +If you don't have a LogDNA account, you can create one on https://logdna.com. Or if you're using macOS w/[Homebrew](https://brew.sh) installed:
the references to `macOS` for where/how to install our cli are probably ok here, just pointing it out

2020-10-07 16:00 UTC, darinspivey commented on .npmrc
> +package-lock=false
I see your point.

2020-10-07 16:01 UTC, darinspivey commented on lib/config.js
> +, DEFAULT_WINTAIL_FILE: '/etc/winTail.ps1'
yeah, not sure 100%, but it's certainly not appropriate for this repo

2020-10-07 17:14 UTC, smusali requested changes
few comments

2020-10-07 17:14 UTC, smusali commented on CONTRIBUTING.md
> +# Developer Guide
@darinspivey, can you remove all the `Developer Guide` part since we have already removed `grunt`-specific stuff and the information here below is obsolete? Basically, let's keep only `Github Workflow` and later we can revisit this file.

2020-10-07 17:14 UTC, smusali commented on README.md
> +## OpenShift Logging
@darinspivey, you can safely remove `OpenShift Logging`

2020-10-07 17:14 UTC, smusali commented on lib/config.js
> +, RESCAN_INTERVAL_K8S: process.RESCAN_INTERVAL_K8S || 10000 // 10 sec
No need for this

2020-10-07 17:14 UTC, smusali commented on lib/file-utilities.js
> +    if (os.platform() !== 'win32' && config.TAIL_MODE === 'unix') {
yup - no need for checking for `win32` and even `unix` - since upcoming versions don't have support that since there is no way we can get that info from the server side as we discussed

Basically, purge `if` case, leave `else`

2020-10-07 17:14 UTC, smusali commented on tools/files/logdna.gpg
> +-----BEGIN PGP PUBLIC KEY BLOCK-----
@darinspivey, this is public GPG key - let's leave this here for now since we are gonna revisit how to properly publish and install the packages.

2020-10-07 17:14 UTC, smusali commented on lib/file-utilities.js
> +    if (os.platform() !== 'win32' && config.TAIL_MODE === 'unix') {
Ooops, @darinspivey, sorry - customers can still use `TAIL_MODE` env variable to set it to `unix` - so, no touch to that.

2020-10-08 18:11 UTC, smusali requested changes
nits

2020-10-08 18:11 UTC, smusali commented on CONTRIBUTING.md
> +## Running the Tests
@darinspivey, need to remove everything below this including all of the `grunt` stuff

2020-10-08 18:11 UTC, smusali commented on lib/config.js
> +, SOCKET_PATH: process.env.LOGDNA_DOCKER_SOCKET
@darinspivey, no need for this one either

2020-10-08 18:59 UTC, darinspivey commented on lib/config.js
> +, SOCKET_PATH: process.env.LOGDNA_DOCKER_SOCKET
good catch

2020-10-08 19:40 UTC, mdeltito commented on .gitignore
> +package-lock.json
if we're moving forward with including the lockfile, this will need to be removed so it can be committed

2020-10-08 19:51 UTC, darinspivey commented on .gitignore
> +package-lock.json
gah! 👍

2020-10-08 19:52 UTC, darinspivey commented on .gitignore
> +package-lock.json
Removed from the ignore and re-generated (and added) the lock file

2020-10-08 21:34 UTC, smusali approved these changes
lgtm!

2020-10-08 21:36 UTC, mdeltito approved these changes

2020-10-08 21:42 UTC, merged